### ISSUE TITLE
State value to set for XYZ has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by oberstel** [iobroker-community-adapters/ioBroker.mpd#3]
There are a bunch of datapoints with wrong type (number instead of string).

State value to set for "mpd.0.**pos**" has to be type "number" but received type "string"
State value to set for "mpd.0.**seek**" has to be type "number" but received type "string"
State value to set for "mpd.0.**id**" has to be type "number" but received type "string"
State value to set for "mpd.0.**bitrate**" has to be type "number" but received type "string"
State value to set for "mpd.0.**elapsed**" has to be type "number" but received type "string"
State value to set for "mpd.0.**song**" has to be type "number" but received type "string"
State value to set for "mpd.0.**volume**" has to be type "number" but received type "string"

**Comment by mcm1957** [comment]
If this issue still exists with current releases b´lease open a new issue.
