### ISSUE TITLE
Play / Pause is not working as expected

### ISSUE THREAD

**Issue by oberstel** [iobroker-community-adapters/ioBroker.mpd#4]
**Describe the bug**  
When trying to resume playback after pause (play), the current track starts from the beginning instead of resuming from last position.   

**To Reproduce**  
1. Go to 'Play' and listen to your favorite music for about 15 seconds
2. Click on 'Pause' to pause playback of the current track (0:15)
3. Click on 'Play' to resume where the playback stoped 
4. Recognize that the track starts from the beginning instead (0:00) of resuming from last position (0:15)

**Expected behavior**  
Play after Pause should resume from last position

**Screenshots & Logfiles**  
-

**Versions:**  
 - Adapter version: 1.0.6 / 1.1.1
 - JS-Controller version: 4.0.24
 - Node version: 16.19.0
 - Operating system: Linux

**Additional context**  

With an other MPD Client (MPD Pilot for iOS), Play/Pause works as expected.

**Comment by raintonr** [comment]
I think this happens because the 'play' button sends an argument zero with the `play` command:

https://github.com/iobroker-community-adapters/ioBroker.mpd/blame/master/main.js#L88

I don't see why you would ever actually need to send that argument TBH.

**Comment by raintonr** [comment]
Fixed.
